require_relative 'lanes/build_lane'
require_relative 'lanes/test_lane'

default_platform(:ios)

platform :ios do
  desc "Build Application"
  lane :build do
    build_lane
  end

  desc "Test Application"
  lane :test do
    test_lane
  end
end