name: PeakTrack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile-check:
    name: Compilation check
    runs-on: macos-26

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "26.0.1"

      - name: Set up Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.2'
          bundler-cache: true

      - name: Cache Homebrew
        uses: actions/cache@v3
        with:
          path: /usr/local/Homebrew
          key: brew-${{ runner.os }}-swiftgen
          restore-keys: brew-${{ runner.os }}-

      - name: Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Build
        run: bundle exec fastlane build
        env:
          LC_ALL: en_US.UTF-8
          LANG: en_US.UTF-8

      - name: Test
        run: bundle exec fastlane test
        env:
          LC_ALL: en_US.UTF-8
          LANG: en_US.UTF-8

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            fastlane/test_output
            fastlane/logs
            **/*.xcresult
